#pragma once
#ifndef _RETXT_ISO639_INCLUDED
#define _RETXT_ISO639_INCLUDED

#include "globalUtilities.hpp"

namespace retxt
{
	enum ISO6391LanguageCode : byte
    {
        aa = 1,
        ab,
        af,
        ak,
        sq,
        am,
        ar,
        an,
        hy,
        as,
        av,
        ae,
        ay,
        az,
        ba,
        bm,
        eu,
        be,
        bn,
        bh,
        bi,
        bs,
        br,
        bg,
        my,
        ca,
        ch,
        ce,
        zh,
        cu,
        cv,
        kw,
        co,
        cr,
        cs,
        da,
        dv,
        nl,
        dz,
        en,
        eo,
        et,
        ee,
        fo,
        fj,
        fi,
        fr,
        fy,
        ff,
        ka,
        de,
        gd,
        ga,
        gl,
        gv,
        el,
        gn,
        gu,
        ht,
        ha,
        he,
        hz,
        hi,
        ho,
        hr,
        hu,
        ig,
        is,
        io,
        ii,
        iu,
        ie,
        ia,
        id,
        ik,
        it,
        jv,
        ja,
        kl,
        kn,
        ks,
        kr,
        kk,
        km,
        ki,
        rw,
        ky,
        kv,
        kg,
        ko,
        kj,
        ku,
        lo,
        la,
        lv,
        li,
        ln,
        lt,
        lb,
        lu,
        lg,
        mk,
        mh,
        ml,
        mi,
        mr,
        ms,
        mg,
        mt,
        mn,
        na,
        nv,
        nr,
        nd,
        ng,
        ne,
        no,
        ny,
        oc,
        oj,
        or_,
        om,
        os,
        pa,
        fa,
        pi,
        pl,
        pt,
        ps,
        qu,
        rm,
        ro,
        rn,
        ru,
        sg,
        sa,
        si,
        sk,
        sl,
        se,
        sm,
        sn,
        sd,
        so,
        st,
        es,
        sc,
        sr,
        ss,
        su,
        sw,
        sv,
        ty,
        ta,
        tt,
        te,
        tg,
        tl,
        th,
        bo,
        ti,
        to,
        tn,
        ts,
        tk,
        tr,
        tw,
        ug,
        uk,
        ur,
        uz,
        ve,
        vi,
        vo,
        cy,
        wa,
        wo,
        xh,
        yi,
        yo,
        za,
        zu
    };
    
    enum ISO6392LanguageCode : uint16_t
    {
        und = ((uint16_t)(-1)),
        zxx = 0,
        aar = ISO6391LanguageCode::aa,
        abk = ISO6391LanguageCode::ab,
        afr = ISO6391LanguageCode::af,
        aka = ISO6391LanguageCode::ak,
        alb = ISO6391LanguageCode::sq,
        amh = ISO6391LanguageCode::am,
        ara = ISO6391LanguageCode::ar,
        arg = ISO6391LanguageCode::an,
        arm = ISO6391LanguageCode::hy,
        asm_ = ISO6391LanguageCode::as,
        ava = ISO6391LanguageCode::av,
        ave = ISO6391LanguageCode::ae,
        aym = ISO6391LanguageCode::ay,
        aze = ISO6391LanguageCode::az,
        bak = ISO6391LanguageCode::ba,
        bam = ISO6391LanguageCode::bm,
        baq = ISO6391LanguageCode::eu,
        bel = ISO6391LanguageCode::be,
        ben = ISO6391LanguageCode::bn,
        bih = ISO6391LanguageCode::bh,
        bis = ISO6391LanguageCode::bi,
        bos = ISO6391LanguageCode::bs,
        bre = ISO6391LanguageCode::br,
        bul = ISO6391LanguageCode::bg,
        bur = ISO6391LanguageCode::my,
        cat = ISO6391LanguageCode::ca,
        cha = ISO6391LanguageCode::ch,
        che = ISO6391LanguageCode::ce,
        chi = ISO6391LanguageCode::zh,
        chu = ISO6391LanguageCode::cu,
        chv = ISO6391LanguageCode::cv,
        cor = ISO6391LanguageCode::kw,
        cos = ISO6391LanguageCode::co,
        cre = ISO6391LanguageCode::cr,
        cze = ISO6391LanguageCode::cs,
        dan = ISO6391LanguageCode::da,
        div = ISO6391LanguageCode::dv,
        dut = ISO6391LanguageCode::nl,
        dzo = ISO6391LanguageCode::dz,
        eng = ISO6391LanguageCode::en,
        epo = ISO6391LanguageCode::eo,
        est = ISO6391LanguageCode::et,
        ewe = ISO6391LanguageCode::ee,
        fao = ISO6391LanguageCode::fo,
        fij = ISO6391LanguageCode::fj,
        fin = ISO6391LanguageCode::fi,
        fre = ISO6391LanguageCode::fr,
        fry = ISO6391LanguageCode::fy,
        ful = ISO6391LanguageCode::ff,
        geo = ISO6391LanguageCode::ka,
        ger = ISO6391LanguageCode::de,
        gla = ISO6391LanguageCode::gd,
        gle = ISO6391LanguageCode::ga,
        glg = ISO6391LanguageCode::gl,
        glv = ISO6391LanguageCode::gv,
        gre = ISO6391LanguageCode::el,
        grn = ISO6391LanguageCode::gn,
        guj = ISO6391LanguageCode::gu,
        hat = ISO6391LanguageCode::ht,
        hau = ISO6391LanguageCode::ha,
        heb = ISO6391LanguageCode::he,
        her = ISO6391LanguageCode::hz,
        hin = ISO6391LanguageCode::hi,
        hmo = ISO6391LanguageCode::ho,
        hrv = ISO6391LanguageCode::hr,
        hun = ISO6391LanguageCode::hu,
        ibo = ISO6391LanguageCode::ig,
        ice = ISO6391LanguageCode::is,
        ido = ISO6391LanguageCode::io,
        iii = ISO6391LanguageCode::ii,
        iku = ISO6391LanguageCode::iu,
        ile = ISO6391LanguageCode::ie,
        ina = ISO6391LanguageCode::ia,
        ind = ISO6391LanguageCode::id,
        ipk = ISO6391LanguageCode::ik,
        ita = ISO6391LanguageCode::it,
        jav = ISO6391LanguageCode::jv,
        jpn = ISO6391LanguageCode::ja,
        kal = ISO6391LanguageCode::kl,
        kan = ISO6391LanguageCode::kn,
        kas = ISO6391LanguageCode::ks,
        kau = ISO6391LanguageCode::kr,
        kaz = ISO6391LanguageCode::kk,
        khm = ISO6391LanguageCode::km,
        kik = ISO6391LanguageCode::ki,
        kin = ISO6391LanguageCode::rw,
        kir = ISO6391LanguageCode::ky,
        kom = ISO6391LanguageCode::kv,
        kon = ISO6391LanguageCode::kg,
        kor = ISO6391LanguageCode::ko,
        kua = ISO6391LanguageCode::kj,
        kur = ISO6391LanguageCode::ku,
        lao = ISO6391LanguageCode::lo,
        lat = ISO6391LanguageCode::la,
        lav = ISO6391LanguageCode::lv,
        lim = ISO6391LanguageCode::li,
        lin = ISO6391LanguageCode::ln,
        lit = ISO6391LanguageCode::lt,
        ltz = ISO6391LanguageCode::lb,
        lub = ISO6391LanguageCode::lu,
        lug = ISO6391LanguageCode::lg,
        mac = ISO6391LanguageCode::mk,
        mah = ISO6391LanguageCode::mh,
        mal = ISO6391LanguageCode::ml,
        mao = ISO6391LanguageCode::mi,
        mar = ISO6391LanguageCode::mr,
        may = ISO6391LanguageCode::ms,
        mlg = ISO6391LanguageCode::mg,
        mlt = ISO6391LanguageCode::mt,
        mon = ISO6391LanguageCode::mn,
        nau = ISO6391LanguageCode::na,
        nav = ISO6391LanguageCode::nv,
        nbl = ISO6391LanguageCode::nr,
        nde = ISO6391LanguageCode::nd,
        ndo = ISO6391LanguageCode::ng,
        nep = ISO6391LanguageCode::ne,
        nor = ISO6391LanguageCode::no,
        nya = ISO6391LanguageCode::ny,
        oci = ISO6391LanguageCode::oc,
        oji = ISO6391LanguageCode::oj,
        ori = ISO6391LanguageCode::or_,
        orm = ISO6391LanguageCode::om,
        oss = ISO6391LanguageCode::os,
        pan = ISO6391LanguageCode::pa,
        per = ISO6391LanguageCode::fa,
        pli = ISO6391LanguageCode::pi,
        pol = ISO6391LanguageCode::pl,
        por = ISO6391LanguageCode::pt,
        pus = ISO6391LanguageCode::ps,
        que = ISO6391LanguageCode::qu,
        roh = ISO6391LanguageCode::rm,
        rum = ISO6391LanguageCode::ro,
        run = ISO6391LanguageCode::rn,
        rus = ISO6391LanguageCode::ru,
        sag = ISO6391LanguageCode::sg,
        san = ISO6391LanguageCode::sa,
        sin = ISO6391LanguageCode::si,
        slo = ISO6391LanguageCode::sk,
        slv = ISO6391LanguageCode::sl,
        sme = ISO6391LanguageCode::se,
        smo = ISO6391LanguageCode::sm,
        sna = ISO6391LanguageCode::sn,
        snd = ISO6391LanguageCode::sd,
        som = ISO6391LanguageCode::so,
        sot = ISO6391LanguageCode::st,
        spa = ISO6391LanguageCode::es,
        srd = ISO6391LanguageCode::sc,
        srp = ISO6391LanguageCode::sr,
        ssw = ISO6391LanguageCode::ss,
        sun = ISO6391LanguageCode::su,
        swa = ISO6391LanguageCode::sw,
        swe = ISO6391LanguageCode::sv,
        tah = ISO6391LanguageCode::ty,
        tam = ISO6391LanguageCode::ta,
        tat = ISO6391LanguageCode::tt,
        tel = ISO6391LanguageCode::te,
        tgk = ISO6391LanguageCode::tg,
        tgl = ISO6391LanguageCode::tl,
        tha = ISO6391LanguageCode::th,
        tib = ISO6391LanguageCode::bo,
        tir = ISO6391LanguageCode::ti,
        ton = ISO6391LanguageCode::to,
        tsn = ISO6391LanguageCode::tn,
        tso = ISO6391LanguageCode::ts,
        tuk = ISO6391LanguageCode::tk,
        tur = ISO6391LanguageCode::tr,
        twi = ISO6391LanguageCode::tw,
        uig = ISO6391LanguageCode::ug,
        ukr = ISO6391LanguageCode::uk,
        urd = ISO6391LanguageCode::ur,
        uzb = ISO6391LanguageCode::uz,
        ven = ISO6391LanguageCode::ve,
        vie = ISO6391LanguageCode::vi,
        vol = ISO6391LanguageCode::vo,
        wel = ISO6391LanguageCode::cy,
        wln = ISO6391LanguageCode::wa,
        wol = ISO6391LanguageCode::wo,
        xho = ISO6391LanguageCode::xh,
        yid = ISO6391LanguageCode::yi,
        yor = ISO6391LanguageCode::yo,
        zha = ISO6391LanguageCode::za,
        zul = ISO6391LanguageCode::zu,
        ace,
        ach,
        ada,
        ady,
        afh,
        ain,
        akk,
        ale,
        alg,
        alt,
        ang,
        anp,
        apa,
        arc,
        arn,
        arp,
        arw,
        ast,
        ath,
        aus,
        awa,
        bad,
        bai,
        bal,
        ban,
        bas,
        bej,
        bem,
        ber,
        bho,
        bik,
        bin,
        bla,
        bra,
        btk,
        bua,
        bug,
        byn,
        cad,
        cai,
        car,
        ceb,
        chb,
        chg,
        chk,
        chm,
        chn,
        cho,
        chp,
        chr,
        chy,
        cmc,
        cnr,
        cop,
        cpe,
        cpf,
        cpp,
        crh,
        csb,
        dak,
        dar,
        day,
        del,
        den,
        dgr,
        din,
        doi,
        dsb,
        dua,
        dum,
        dyu,
        efi,
        egy,
        eka,
        elx,
        enm,
        ewo,
        fan,
        fat,
        fil,
        fon,
        frm,
        fro,
        frr,
        frs,
        fur,
        gaa,
        gay,
        gba,
        gez,
        gil,
        gmh,
        goh,
        gon,
        gor,
        got,
        grb,
        grc,
        gsw,
        gwi,
        hai,
        haw,
        hil,
        him,
        hit,
        hmn,
        hsb,
        hup,
        iba,
        ijo,
        ilo,
        inh,
        iro,
        jbo,
        jpr,
        jrb,
        kaa,
        kab,
        kac,
        kam,
        kar,
        kaw,
        kbd,
        kha,
        khi,
        kho,
        kmb,
        kok,
        kos,
        kpe,
        krc,
        krl,
        kro,
        kru,
        kum,
        kut,
        lad,
        lah,
        lam,
        lez,
        lol,
        loz,
        lua,
        lui,
        lun,
        luo,
        lus,
        mad,
        mag,
        mai,
        mak,
        man,
        mas,
        mdf,
        mdr,
        men,
        mga,
        mic,
        min,
        mis,
        mkh,
        mnc,
        mni,
        mno,
        moh,
        mos,
        mul,
        mun,
        mus,
        mwl,
        mwr,
        myn,
        myv,
        nah,
        nai,
        nap,
        nds,
        new_,
        nia,
        niu,
        nog,
        non,
        nqo,
        nso,
        nub,
        nwc,
        nym,
        nyn,
        nyo,
        nzi,
        osa,
        ota,
        oto,
        paa,
        pag,
        pal,
        pam,
        pap,
        pau,
        peo,
        phi,
        phn,
        pon,
        pra,
        pro,
        raj,
        rap,
        rar,
        rom,
        rup,
        sad,
        sah,
        sai,
        sal,
        sam,
        sas,
        sat,
        scn,
        sco,
        sel,
        sga,
        shn,
        sid,
        sio,
        sma,
        smj,
        smn,
        sms,
        snk,
        sog,
        son,
        srn,
        srr,
        suk,
        sus,
        sux,
        syc,
        syr,
        tai,
        tem,
        ter,
        tet,
        tig,
        tiv,
        tkl,
        tlh,
        tli,
        tmh,
        tog,
        tpi,
        tsi,
        tum,
        tup,
        tut,
        tvl,
        tyv,
        udm,
        uga,
        umb,
        vai,
        vot,
        wak,
        wal,
        war,
        was,
        wen,
        xal,
        yao,
        yap,
        ypk,
        zap,
        zbl,
        zen,
        zgh,
        znd,
        zun,
        zza
    };
}

#endif // _RETXT_ISO639_INCLUDED
